[ubuntu-focal]
url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"

[ubuntu-bionic]
url = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"

[ubuntu-xenial]
url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img"

[debian-11]
url = "http://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2"

[debian-10]
url = "https://cloud.debian.org/images/cloud/buster/20210329-591/debian-10-generic-amd64-20210329-591.qcow2"

[debian-9]
# There is no publicly available "generic" image, but the OpenStack one works
url = "https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2"

[centos-8]
url = "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2"

[centos-7]
url = "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"

[centos-6]
url = "https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2"

[amazonlinux-2]
url = "https://cdn.amazonlinux.com/os-images/2.0.20211001.1/kvm/amzn2-kvm-2.0.20211001.1-x86_64.xfs.gpt.qcow2"
